// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      // return android;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
              'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBqvtGLCLdP7W7o_F13PK8ZPjQjboHBZ-g',
      authDomain: 'social-media-300bc.firebaseapp.com',
      projectId: 'social-media-300bc',
      storageBucket: 'social-media-300bc.firebasestorage.app',
      messagingSenderId: '12140950547',
      appId: '1:12140950547:web:9ac914f9682c002bad3be6',
      measurementId: 'G-7CRWT27H1P');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbylzwXfCInBKScwCdHoOCMGKH4t3qWH0',
    appId: '1:12140950547:android:4cb97b364b2651d4ad3be6',
    messagingSenderId: '12140950547',
    projectId: 'social-media-300bc',
    storageBucket: 'social-media-300bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4TDAK1DEO4ypTbQs5kBLcfuXhIrYm9Q',
    appId: '1:12140950547:ios:8441441fb30d54e2ad3be6',
    messagingSenderId: '12140950547',
    projectId: 'social-media-300bc',
    storageBucket: 'social-media-300bc.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

}